### ISSUE TITLE
Does this plugin uses ~/.ssh/config and possible to use tunnel? 

### ISSUE THREAD

**Issue by ehmkah** [tilln/jmeter-sshmon#15]
Is it possible to use this plugin with configuration from ~/.ssh/config ?
For me it looks that this file is not taken into account. because i configured a hostname in config file and it get "unresolved Address"

Is it possible to use this plugin with a tunneled connection? 
Because i need a tunnel to configure to the host where the interesting data is available

**Comment by tilln** [comment]
Hallo @ehmkah 

The SSH config file is only taken into account if the JMeter property `jmeter.sshmon.sshConfig` is set to the file location.

I'm assuming you have set this?
See https://github.com/tilln/jmeter-sshmon#jump-hosts-since-v13

However, your error suggests it fails to resolve the hostname as perhaps the there is no DNS entry on the JMeter side of the network, before the tunnel/jump host.
This may not work with the underlying library and hasn't been tested.

**Comment by ehmkah** [comment]
It looks like I missed this part in your documentation. Your description looks more or less like the configuration I am using. Si try it. Thanks for your help so far. 👍
